name: untitled1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  qr_code_scanner: ^1.0.1
  flutter_inappwebview: ^6.0.0

  fl_chart: ^0.63.0
  flutter:

    sdk: flutter



  cupertino_icons: ^1.0.8

  youtube_player_flutter: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/logo.png
    - assets/imgs/image 1.png
    - assets/imgs/image 2.png
    - assets/imgs/back (1) 1.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
